### ISSUE TITLE
Maybe Offset for a "play" is not a correct word.

### ISSUE THREAD

**Issue by onekk** [mwganson/joint#1]
Hello, great work.

We have discussed already on FreeCAD forum (same nickname).

Not to criticize, only to be constructive, as said in title, the word offset for a "play" is not appropriate.

Sorry for having done an Issue for a similar thing, it seems the only way to make some "interaction" at least in GitHub.

Regards and thanks for the great work.

Carlo D.

**Comment by mwganson** [comment]
What is wrong with "offset"?

**Comment by onekk** [comment]
Nothing, but some other CAM call this simply a "play" meaning it "room to permit mating or gluing".

Offset has some "mathematics" smell, more related to 2D work when drawing, but:

1) English is not my mother language
2) I'm not an CAD CAM expert, only a sort of "power user"

Regards

Carlo D.

**Comment by onekk** [comment]
No problem, as I have coded something similar, "with less generalization" I have used Play, clearance maybe is more "professional".

2D offset is rather easy to use, and using some tricks will be useful, try to apply an offset of 10mm and then a -10mm using the offset starting wire, and you obtain a different way to make rounded corners.

Regards

Carlo D.
