### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by BanceFC** [mwganson/joint#3]
Box joint appears at weird angle if base is attached to YZ plane.
Inc file is renamed FCStd type.

Thanks for your attention.
[joint.txt](https://github.com/mwganson/joint/files/8597836/joint.txt)
.

**Comment by mwganson** [comment]
Please try with version 0.2022.05.01.

**Comment by BanceFC** [comment]
Thanks for your prompt attention, Mark.
Macro now produces (Box Joint)pocket perpendicular to that which might be expected but is perfectly usable with the angle adjust.


I have noticed one other minor thing/bug(?) That is that macro (Box Joint) applied to face on XY plane is offset to those applied in other planes. Again perfectly usable with 'use odd' > 'true.' Inc file as before renamed FCStd type.

[BoxJointOdd.txt](https://github.com/mwganson/joint/files/8609398/BoxJointOdd.txt)

**Comment by mwganson** [comment]
Both issues are probably related.  No extra processing is done to try to determine which angle to use.  In the case of the use odd property in this case the same result can be had by rotating 180 degrees.

**Comment by BanceFC** [comment]
Closing this, once again thanks.
