### ISSUE TITLE
Position of Generated Pattern Is Unpredictable With Irregular Shaped Pads

### ISSUE THREAD

**Issue by lightingnerd** [mwganson/joint#4]
I am trying to use this macro for designing a parametrized box pattern for laser cutting. I need the box to be robust and I would prefer to avoid exclusively relying on wood glue to support the bottom. In order to do this, I need the holes to not be attached to a corner. 

Unfortunately, there seems to be an unpredictable offset from true center with irregular shapes, and yet I can't identify the cause of the problem, because it looks like the code is inheriting the base position from the parent body. 

To reproduce, 

1. Draw an irregular shape in sketcher.
2. Pad Sketch in Part Designer.
3. Select Face.
4. Execute Macro.
5. Select Box Joint

![image](https://user-images.githubusercontent.com/8975739/193694763-d6b337c7-85e7-430b-9105-2062a269db55.png)

**Comment by lightingnerd** [comment]
![image](https://user-images.githubusercontent.com/8975739/193903754-0497d9dc-933b-4da2-8dea-fea684143c33.png)

I found an alternative method that works well even with the irregular shape:

Replace:
`shape.Placement = fp.Placement.multiply(FreeCAD.Placement(face.CenterOfMass, FreeCAD.Rotation(FreeCAD.Vector(0,0,1),FreeCAD.Vector(x,y,z))))`

With:
`shape.Placement = fp.Placement.multiply(FreeCAD.Placement(face.BoundBox.Center, FreeCAD.Rotation(FreeCAD.Vector(0,0,1),FreeCAD.Vector(x,y,z))))`

**Comment by mwganson** [comment]
I updated.  New version is 0.2022.10.05.

**Comment by lightingnerd** [comment]
Awesome, thanks for keeping this tool going! It's been very helpful!
