### ISSUE TITLE
FreeCAD Link Branch LinkDaily

### ISSUE THREAD

**Issue by kotrans** [mwganson/joint#6]
Hi
I use the following version of FreeCAD:

https://github.com/realthunder/FreeCAD/releases

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1128.26244 +5318 (Git)
Build type: Release
Branch: LinkDaily
Hash: d45d221edcc7a757eb4e4eb638da0db5ed2759aa
Python version: 3.10.8
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.6.3
Locale: German/Switzerland (de_CH)

I always geht the following error-message. It doesn't matter which joint I use.

18:00:33  Traceback (most recent call last):
  File "//.../Roaming/FreeCAD/Macro/Joint.FCMacro", line 1303, in <module>
    makeObject(FP)
  File "//...AppData/Roaming/FreeCAD/Macro/Joint.FCMacro", line 1187, in makeObject
    FP.Joint(joint)
  File "<string>", line 16, in __init__
<class 'RuntimeError'>: Property Unnamed#Joint.AddSubType already exists
18:00:33  1644.75 <App> Document.cpp(4327): Failed to recompute Unnamed#Body: Tip shape is empty
18:00:33  Recompute failed! Please check report view.

![image](https://user-images.githubusercontent.com/119668534/208963659-dd5191b5-6c51-4599-b986-3819491d73fa.png)
It is written: "The shape is empty".

Thanks for your support.

**Comment by mwganson** [comment]
I guess RT has add a property of that same name "AddSubType".  I have removed it from Joint object types.  This property was only used for information to the user, so removing should not affect anything.  Please update and test.  Latest version: 0.2022.12.21

**Comment by kotrans** [comment]
Thanks. This is amazing how fast you solved it. Thanks!
It works perfectly.
Have a nice day!
